spring:
  application:
    name: manager-config
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: myuser
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
---
