spring:
    application:
    name: manager-config
---
### Config DB ###
# Oracle
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: myuser
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
---
# MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

