spring:
  application:
    name: manager-config

---

spring:
  config:
    activate:
      on-profile: oracle
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: myuser
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver

---

spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
