spring:
  application:
    name: manager-config-oracle
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    oracle1:
       url: jdbc:oracle:thin:@localhost:1521:xe
       username: myuser
       password: admin
       driver-class-name: oracle.jdbc.OracleDriver
     oracle2:
       url: jdbc:oracle:thin:@localhost:1521:xe
       username: order_manager
       password: admin
       driver-class-name: oracle.jdbc.OracleDriver