spring:
  application:
    name: manager-config-mysql
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver